substitutions:
  _IMAGE: us-central1-docker.pkg.dev/$PROJECT_ID/screenly/web

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --file
      - apps/web/Dockerfile
      - --tag
      - ${_IMAGE}:$BUILD_ID
      - --tag
      - ${_IMAGE}:latest
      - .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - --all-tags
      - ${_IMAGE}

images:
  - ${_IMAGE}:$BUILD_ID
  - ${_IMAGE}:latest
